### ISSUE TITLE
Not getting disconnect events

### ISSUE THREAD

**Issue by ebrensi** [wildfoundry/dataplicity-lomond#28]
Hi, this is a great looking Websocket client implementation!  I'd love to use it but I need to iron out a few details. Perhaps I'm misunderstanding something, but I am not getting disconnect events when I intentionally disconnect my laptop in order to test Lomond's event functionality.   I've tried using threading explicitly, via gevent monkey patching, and explicitly using greenlets for the event loop.  I've tried both the `connect()` method and `persist()`.  Here is the test script I'm running:
```
# import gevent.monkey
# gevent.monkey.patch_all()

import lomond
import lomond.persist
import datetime
import threading

log = logging


class WebsocketClient:
    def __init__(self, url):
        self.socket = lomond.websocket.WebSocket(url)

    def run(self):
        def _event_loop():
            print("socket client {} OPENED".format(self.socket))

            #for event in lomond.persist.persist(self.socket):
            for event in self.socket:
                self.on_event(event)

            print("socket client {} CLOSED".format(self.socket))

        # gevent.spawn(_event_loop)
        # gevent.sleep(0)
        threading.Thread(target=_event_loop).start()

    def stop(self):
        self.socket.close()

    def on_event(self, event):
        print("{} event: {} ".format(self.socket, event))
        print("")


client = WebsocketClient("ws://echo.websocket.org")
client.run()

gevent.sleep(5)

try:
    while True:
        client.socket.send_text(
            unicode("hello {}".format(datetime.datetime.now()))
        )
        gevent.sleep(10)
except:
    client.stop()
```

I'm running Python 2.7,  and I have tried with 3.6 as well.  What happens is that if I disconnect from the LAN, I continue to receive poll events. Instead of getting a disconnect event, it just keeps going.  The loop that periodically sends messages doesn't raise an Exception either.

**Comment by willmcgugan** [comment]
Sorry for the delay in responding.

You will get a Disconnected event if the server closes (gracefully or not), or if you call `close` on the websocket.

I've found that the network stack will not respond to pulling the ethernet cable for some time. And the exact behaviour seems to be platform dependant. Normally thats a good thing. You can pull an ethernet cable out and then plug it back in and nothing typically breaks.

If you want to be handle that case more precisely, you can do it at the application level. For instance if the server sends pings, then you could close the websocket if you haven't received a ping in  a while. Or you could send pings, and close if you don't receive the pong in time.

That is something that might be worthwhile adding to Lomond, an 'auto_ping' setting that auto-closes the websocket if it doesn't receive a timely response...
