### ISSUE TITLE
websocket inside of a thread

### ISSUE THREAD

**Issue by gdanko** [wildfoundry/dataplicity-lomond#29]
Hi,
I am building a package to communicate with a websocket-based API for a home automation system. I need to be able to send a command (say put the hub into pairing mode to add a new device) and wait to see if the device was added.

Right now I can create the websocket, send the request, then I get back ack that the request was successful. The script ends there.

I can use websocket-client and run_forever() but that is blocking and I cannot send to it.

I am playing with lomond and it looks like a nice package. Is there a way I can put the websocket in a thread so it is not blocking, but send to it if I want to do something?

Example:
1) Connect to the websocket
2) Send a "setActivePlace" request
Now I am good to go
3) Wait for an event that a motion sensor has been tripped
4) Send a payload to the websocket to do X
5) Receive confirmation that the request was sent
6) Wait for an event stating that X was completed
7) Repeat

**Comment by gdanko** [comment]
Now this code works. My only concern is that I am using the poll period to look at the queue. I am trying to find a way that doesn't require a 5 second interval.

The other issue is that I have that time.sleep(5) in there to wait until I have the place_id before sending additional commands.

Any ideas on how to overcome these two items?

`#!bin/python

from lomond import WebSocket
from lomond.persist import persist
from pprint import pprint
from threading import Thread
import json
import queue
import sys
import time

def process_result(result):
	global places
	global account_id
	global account_address
	global place_id
	global place_address
	if "type" in result:
		if result["type"] == "SessionCreated":
			if "payload" in result and "attributes" in result["payload"]:
				if "places" in result["payload"]["attributes"]:
					places = [place for place in result["payload"]["attributes"]["places"] if place["placeName"] == "My Home"]
					if len(places) == 1:
						place = places[0]
						account_id = place["accountId"]
						account_address = "SERV:account:{}".format(account_id)
						place_id = place["placeId"]
						place_address = "SERV:place:{}".format(place_id)				
					else:
						print("place not found. please create a proper exception.")
						sys.exit(1)
				else:
					print("no places returned. please create a proper exception.")
					sys.exit(1)
			else:
				print("no payload returned. please create a proper exception.")
				sys.exit(1)
		else:
			print("something went wrong. please create a proper exception.")
			sys.exit(1)

def validate_json(string):
	if string:
		try:
			hash = json.loads(string)
			return hash
		except:
			return None
	else:
		return None

def process_output(content):
	result = validate_json(content)
	if result:
		pprint(result)
		print("")
		if "type" in result:
			if result["type"] == "SessionCreated":
				process_result(result)

ws_uri = "wss://bc.irisbylowes.com/websocket"
token = "xxxx"
cookie = "irisAuthToken={}".format(token)
q = queue.Queue()
ws = WebSocket(ws_uri)
ws.add_header("Cookie".encode("utf-8"), cookie.encode("utf-8"))

def run():
	for event in ws:
		if event.name == "poll":
			item = q.get()
			ws.send_text(item)
		if event.name == "text":
			process_output(event.text)
			#ws.send_text(event.text)

Thread(target=run).start()
place_id = None

time.sleep(5)
payload = {
	"type": "sess:SetActivePlace",
	"headers": {
		"destination":"SERV:sess:",
		"correlationId": "78f7d29a-222e-4976-9d2b-d1f553cf8881",
		"isRequest" :True
	},
	"payload": {
		"messageType": "sess:SetActivePlace",
		"attributes": {
			"placeId": place_id
		}
	}
}
q.put(json.dumps(payload))

payload = {
	'headers': {
		'correlationId': '790525f5-171f-4533-a952-0dcafb9b5310',
		'destination': 'DRIV:dev:xxxx',
		'isRequest': True
	},
	'payload': {
		'attributes': {
			'dim:brightness': 25
		},
		'messageType': 'base:SetAttributes'
	},
	'type': 'base:SetAttributes'
}
q.put(json.dumps(payload))`

**Comment by willmcgugan** [comment]
The polling is intended for regular house-keeping type tasks. It's not useful if you need to respond to anything in realtime.

You can use the websocket object to send packets from the main thread, that's not a problem. Leave the thread containing the websocket loop responsible for *receiving* messages. When you get a message push it on to your queue. Then in your main thread you can do `q.get` which will block until your expected message arrives.

Hope that helps...

**Comment by gdanko** [comment]
Thanks Will, that the messages that need to be sent come from the main thread. They have to. Let me show you an example script.

```
#!/usr/bin/env python3

import sys
from iris.capabilities.account import Account
from iris.capabilities.place import Place
from iris.core import Iris

iris = Iris(
	account="gd",
	place_name="My Home",
	#debug=True
)

d = Dimmer(iris=iris)
d.set_attribute(device="Dimmer1", namespace="dim", attribute="brightness", value=25) # The payload from this method would be SENT to the websockt
pprint(d.response)

# Wait a while

lock = DoorLock(iris=iris)
lock.set_attribute(device="Door1", namespace="dim", attribute="lockstate", value="locked")
pprint(lock.response)
```
So all I care about in terms of events is the responses from the commands I sent. This is why my queue.get() needs to be inside the websocket loop. The queue.put()s all take place externally.

Does that make sense?

**Comment by willmcgugan** [comment]
As far as I can tell you are pushing your messages on to a queue in the main thread, which the websocket then picks off and sends. I doubt that is necessary, you can send them directly in the main thread and avoid the additional ~5 second delay.

I'm not familiar with the protocol you're using, but if you need to wait for a response, you will a queue, a lock, or some other kind of synchronisation primitive.

**Comment by gdanko** [comment]
how can I send my messages from the main thread to the websocket thread? I have not figured out how. :(

**Comment by willmcgugan** [comment]
You can send messages to the server from the main thread with `ws.send_text` You will *receive* messages from the server in your websocket loop (within `run`).

**Comment by gdanko** [comment]
That worked. Then my last problem is hopefully an easy one.

```
def run():
	for event in ws:
		if event.name == "poll":
			item = q.get()
			ws.send_text(item)
		if event.name == "text":
			process_output(event.text)
			#ws.send_text(event.text)

Thread(target=run).start()
place_id = None

time.sleep(5)
payload = {
	"type": "sess:SetActivePlace",
	"headers": {
		"destination":"SERV:sess:",
		"correlationId": "78f7d29a-222e-4976-9d2b-d1f553cf8881",
		"isRequest" :True
	},
	"payload": {
		"messageType": "sess:SetActivePlace",
		"attributes": {
			"placeId": place_id
		}
	}
}
ws.send_text(json.dumps(payload))
```
Look at the time.sleep(5)
It seems hokey so I did something like this. Does this look sane?
```
def run():
	global ready
	for event in ws:
		if event.name == "ready":
			ready = True
		elif event.name == "text":
			process_output(event.text)

Thread(target=run).start()

while ready == False:
	time.sleep(1)
# start ws.send_texting here
```

**Comment by willmcgugan** [comment]
You've got the right idea, but what you need is a `threading.Event` object. Set it in the websocket loop, and wait for it in your main loop...

**Comment by gdanko** [comment]
Working like a champ. Thanks!
