### ISSUE TITLE
Lomond logging

### ISSUE THREAD

**Issue by gdanko** [wildfoundry/dataplicity-lomond#30]
My package which uses lomond utilizes python logging. If I set my internal logger's log level to debug I also get lomond debug output. This is how I configure my logger.

```
def configure_logger(loggerid=None, debug=False):
	if loggers.get(loggerid):
		return loggers.get(loggerid)
	else:
		level = logging.DEBUG if debug == True else logging.INFO

		logger = logging.getLogger(loggerid)
		handler = logging.StreamHandler()
		formatter = logging.Formatter("%(levelname)s %(message)s")
		handler.setFormatter(formatter)
		logger.addHandler(handler)
		logger.setLevel(level)
		logger.propagate = False
		loggers[loggerid] = logger
	return logger
```
This SHOULD isolate my logger from lomond's as I am setting propagate to false. Am I missing something here?

**Comment by willmcgugan** [comment]
Logging is notoriously awkward to set up. I'm afraid there is not enough information here to diagnose your problem. I can't see which loggers are being configured.

I'd highly recommend using `dictConfig` or `fileConfig` to set up your logging.

Lomond itself doesn't do anything novel with logging. There is a single top level logger called `lomond`

**Comment by gdanko** [comment]
Okay thanks.
