### ISSUE TITLE
Can't run lomond on python3

### ISSUE THREAD

**Issue by grctest** [wildfoundry/dataplicity-lomond#31]
Can't seem to run python3 within a virtual environment on Ubuntu 17.10:

```
(HUG) btsapi@api:~$ python3 lomond.py
Traceback (most recent call last):
  File "lomond.py", line 1, in <module>
    from lomond.websocket import WebSocket
  File "/home/btsapi/lomond.py", line 1, in <module>
    from lomond.websocket import WebSocket
ModuleNotFoundError: No module named 'lomond.websocket'; 'lomond' is not a package
```

I tried compiling the source too, it shows as requirements fulfilled yet when I try to run a hello world it fails immediately when importing lomond.

Any tips on how to setup lomond? Does it not work for python3.x?

**Comment by willmcgugan** [comment]
Try renaming your `lomond.py` to something else...
