### ISSUE TITLE
Event loop blocks execution of program

### ISSUE THREAD

**Issue by jeffmikels** [wildfoundry/dataplicity-lomond#33]
It probably is by design, but the event loop:

```python
for event in ws:
```

continually polls the websocket for events, and that blocks the rest of my script from executing. Is there a way to yield the batch of queued events and return control to my script?

**Comment by willmcgugan** [comment]
Yeah, that's by design, but it is straightforward to run the event loop from a thread. You might want to consider having a thread that pushes events on to a `threading.Queue` object that you can manage from your main thread.
