### ISSUE TITLE
Select vs *Poll

### ISSUE THREAD

**Issue by s0undt3ch** [wildfoundry/dataplicity-lomond#39]
select cannot select on file descriptor numbers > FD_SETSIZE (1024 on
most systems), limiting the number of connections that can be created.

It does not necessarily have to be websocket connections, but if the application already has a high number of file descriptor usage, then the websocket connection would fail...

So, why not use any available poll implementation?

I found out about lomond while searching for a python websocket python implementation. One of the search results was your blog post and the reasoning why lomond was created. You mentioned websocket-client. They seemed to have replaced select with poll, https://github.com/websocket-client/websocket-client/pull/375

Anyway, any plans to support poll instead of select?

**Comment by willmcgugan** [comment]
I wasn't aware of that limitation. It shouldn't be hard to swap out select in favour of poll. I'll add that to the todo list.

**Comment by willmcgugan** [comment]
v0.1.4 (in PyPi) will now use poll on lunx and kqueue in MacOS. Thanks for reporting this!
