### ISSUE TITLE
Session close timeout fails due to mixing relative and absolute times

### ISSUE THREAD

**Issue by gmyers18** [wildfoundry/dataplicity-lomond#50]
The `sent_close_time` in `WebSocket.State` is an **absolute** epoch time (see [line 240](https://github.com/wildfoundry/dataplicity-lomond/blob/e37406c39d481ccb28dee43b221c0e2f6e595c44/lomond/websocket.py#L240)).  But `Session._check_close_timeout()` performs a comparison which is based on elapsed seconds **relative** to the start of the session (see [line 262](https://github.com/wildfoundry/dataplicity-lomond/blob/e37406c39d481ccb28dee43b221c0e2f6e595c44/lomond/session.py#L262)), thus the close timeout will never fire.  A simple fix would be to store "elapsed session time" in `sent_close_time`.

On a related note, it is a bit counter-intuitive to me that every call to `WebSocket.close()` updates the `sent_close_time`. Thus, for a case where multiple close packets happen to be sent, the close timeout check is always relative to the **last** packet rather than the **first**.  If one is relying on the close timeout check to close out a session where the server fails to respond, and there is a programming error where `close()` is being called periodically in a loop, then the timeout will likely never succeed.

**Comment by willmcgugan** [comment]
Fixed in 0.2.2
