### ISSUE TITLE
WebSocket close by remote server results in non-graceful disconnection

### ISSUE THREAD

**Issue by gmyers18** [wildfoundry/dataplicity-lomond#54]
In 0.2.2 I'm observing that a WebSocket close initiated by the remote server results in a non-graceful `Disconnected` event.  As far as I can tell this is a regression relative to 0.2.1.

This appears to be due to a small change in the main session `run()` loop, where an `is_active` check was removed in the no data case.  I believe this case is triggered when the socket is closed because the selector triggers as readable, but there is no data.  See the change [here](https://github.com/wildfoundry/dataplicity-lomond/commit/fe33e3f032e206cc5386fb839f1cefdbd3c63b37#diff-47e18c92a2e61d31deb894529bda889dL398) on lines 398-400 on the left-hand side.  Restoring these lines appears to fix the issue.

I'm attaching a test case that should produce non-graceful behavior.  This is based on `test_simple_run()` from test_session.py, but adds the necessary bytes for a close to the payload.  Also, note the `session.websocket.state.session = session` code on line 45 of the diff file.  This feels pretty hackish but without it I ran into a different issue about not being able to set the `sent_close_time` in `WebSocket.close()` because the session was not defined in the WebSocket state.

[repro_test.diff](https://github.com/wildfoundry/dataplicity-lomond/files/2000852/repro_test.diff.txt)

**Comment by willmcgugan** [comment]
I guess that's on Windows again?

**Comment by gmyers18** [comment]
For sure on Windows.  I did a very quick test and I believe I'm observing it on Linux (CentOS 7) as well.

**Comment by willmcgugan** [comment]
Thanks. Released 0.2.3 with the fix.

**Comment by willmcgugan** [comment]
Actually, there may be a deeper issue that that. The test passes, but I see non graceful closes when it should be graceful.

**Comment by gmyers18** [comment]
FWIW, I tested the new 0.2.3 release with the simple experiment where I first noticed this and I'm now seeing graceful closes.  This is on both Windows and Linux.  I'm happy to run some further experiments if that might help get to the bottom of this, but for now I'm not sure of the conditions needed to produce a non-graceful case.

**Comment by willmcgugan** [comment]
My mistake. The server I was testing against was doing a non-graceful close. Lomond was doing the right thing.
