### ISSUE TITLE
Multiprocessing with Lomond?

### ISSUE THREAD

**Issue by kpei** [wildfoundry/dataplicity-lomond#59]
Is it possible right now to spin up multiple instances of the websocket with multiprocessing?

I tried a quick check with pickling the websocket component shows that it may not be possible

```
ws = WebSocket('wss://...')
pickle.dumps(ws)

TypeError: can't pickle wsaccel.utf8validator.Utf8Validator objects
```

**Comment by willmcgugan** [comment]
Not currently. It wouldn't be too hard to make WebSocket pickleable.

Not sure it would be much better than just serialising the URL and any parameters you need. There is very little overhead in the WebSocket constructor so you could just create instances as needed.
