### ISSUE TITLE
Example of connecting using ssl/https

### ISSUE THREAD

**Issue by m-menon** [wildfoundry/dataplicity-lomond#66]
hi, is there an example how this could be used to connect using ssl? I tried the examples in a few different ways but couldn't get it to work. thanks

**Comment by willmcgugan** [comment]
If you connect to a websocket URL that starts with `wss://` it will use SSL.

**Comment by m-menon** [comment]
Thanks but I seem to have spent the whole afternoon trying to get it to connect :) ...  I think I probably exhausted every way I can think (both ws:// wss:// ... using public ip, fqdn etc) of .... Is there a way(need?) to specify the ssl certs? I am trying to connect this to a third party service running on one of my own servers. So I pretty much have access/control over everything.

**Comment by willmcgugan** [comment]
Can you try connecting to the URL in your browser, but replace `wss` with `https`. You should she a message like 'no upgrade header'. Just to confirm that endpoint is serving websockets...

**Comment by willmcgugan** [comment]
If it seems to be serving websockets over SSL, you could enable debug logging to see if there are any clues:

```python
import logging
logging.basicConfig()

logging.getLogger().setLevel(logging.DEBUG)

from lomond import WebSocket

ws = WebSocket(YOUR WEBSOCKET URL)
for event in ws:
    print(event)
```

**Comment by m-menon** [comment]
I can use the web browser with js websocket and it connects with exactly the same url. For example the below code works perfectly fine in a browser

```
    <script type="text/javascript">
    $.ajax({
			// Authenticate
            url: "https://gxtest.example.com/xapi/nsession",
            dataType: "json",
            type: "POST",
            data: {
                email: "username",
                password: "password"
            },
            success: function(sessionResponse){
                console.log(sessionResponse);
                openWS();
            }
        });

        // Open Websocket
		var openWS = function(){
            var socket;
            socket = new WebSocket('wss://gxtest.example.com/xapi/xsocket');

            socket.onclose = function (event) {
                console.log("WebSocket closed");
            };

            socket.onmessage = function (event) {
                console.log(event.data);
            };
        };
    </script>
```

**Comment by m-menon** [comment]
Sure, let me try what you mentioned

**Comment by m-menon** [comment]
This is the result
```
Connecting(url='wss://gxtest.example.com/xapi/xsocket')
DEBUG:lomond:unable to connect
ConnectFail('unable to connect')

```

**Comment by m-menon** [comment]
When I replace it with the localhost Ip address I get the following
```
Connecting(url='ws://127.0.0.1:8080/xapi/xsocket')
Connected(url='ws://127.0.0.1:8080/xapi/xsocket')
DEBUG:lomond:<PollSelector> created
Rejected(<response HTTP/1.1 503 Endpoint Creation Failed>, 'Websocket upgrade failed (code=503)')
Disconnected('closed', graceful=True)
```

I am running an Apache ssl proxy terminator but the js websocket ( used from a browser ) connects fine ... and I can see data being streamed

**Comment by willmcgugan** [comment]
Looks like its failing very early. What version of Python are you running? And have you got the latest Lomond from PyPi ?

**Comment by m-menon** [comment]
I can run either of these versions as I have these on the server
Python 2.7.15rc1
Python 3.6.5

My last try was with python 2

And this is how I installed Lomond couple of hours earlier
`pip install lomond`

**Comment by willmcgugan** [comment]
Should be good. I would suspect certs at this point. Lomond doesn't have a way of disabling certificate validation, although there is a ticket for it.

I think this should disable cert validation (on py2.7). Can you try this:

```
PYTHONHTTPSVERIFY=0 python yourscript.py
```

**Comment by m-menon** [comment]
Tried that too ... the same error as before
```
Connecting(url='wss://gxtest.example.com/xapi/xsocket')
DEBUG:lomond:unable to connect
ConnectFail('unable to connect')
```

**Comment by willmcgugan** [comment]
Let me do an interim build with some verbose debugging. It should work, SSL has been thoroughly tested, but clearly something is going wrong.

**Comment by m-menon** [comment]
Alrighty, cool

**Comment by willmcgugan** [comment]
Trying installing `lomond==0.2.6a0` then run with debug logging.

**Comment by m-menon** [comment]
How do I get that version? thanks

**Comment by willmcgugan** [comment]
```
pip install lomond==0.2.6a0
```

**Comment by m-menon** [comment]
I tried that already
```
  Could not find a version that satisfies the requirement lomond==0.2.6a0 (from versions: 0.1.0a0, 0.1.0, 0.1.1, 0.1.2, 0.1.3a0, 0.1.3, 0.1.4, 0.1.5, 0.1.6a0, 0.1.6a1, 0.1.6a2, 0.1.6a3, 0.1.6, 0.1.7a0, 0.1.8, 0.1.9a0, 0.1.9, 0.1.10a0, 0.1.10, 0.1.11, 0.1.12, 0.1.13a0, 0.1.13, 0.1.14, 0.1.15, 0.1.16a0, 0.1.16a1, 0.1.16a2, 0.1.16a3, 0.1.16a4, 0.1.16a5, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5a0, 0.2.5)
No matching distribution found for lomond==0.2.6a0
```

**Comment by m-menon** [comment]
It did work with pip3 though ... so let me test

**Comment by willmcgugan** [comment]
Pypi sometimes take a few minutes to update.

**Comment by m-menon** [comment]
```
Connecting(url='wss://gxtest.example.com/xapi/xsocket')
DEBUG:lomond:wrapping socket
DEBUG:lomond:wrapped socket <ssl.SSLSocket object at 0x7ff96c398b18>
DEBUG:lomond:socket error connecting to ('127.0.0.1', 443); [Errno 111] Connection refused
DEBUG:lomond:unable to connect
ConnectFail('unable to connect')

```

**Comment by m-menon** [comment]
I am running this from the same server where the service is running ... and if I copy the html/javascript code above that uses websocket, it does connect and streams the data just fine

**Comment by m-menon** [comment]
I am starting to think this is related to the socket connection on the other application. I am probing that now

**Comment by willmcgugan** [comment]
That is odd. But everything is pointing to some kind of local configuration issue.

Does this raise any errors?

```python
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("YOR URL", 443))
```

**Comment by willmcgugan** [comment]
I think you get that error when making http requests to an https endpoint...

**Comment by m-menon** [comment]
hi @willmcgugan I got a reply from the maintainer of the other application. He suspects a bug and they are in the process of checking it.

**Comment by m-menon** [comment]
I should know in a while ... in the meantime thanks a zillion for your time ....

**Comment by willmcgugan** [comment]
Ok. Let me know if you find anything out.

**Comment by m-menon** [comment]
Sure, thanks

**Comment by m-menon** [comment]
It turned out to be a problem with the SSL termination on the load balancer. What's (a little) strange is that when using javascript + websocket from a browser, it worked smooth all the time. I tried lomond with another machine, this time with no strange forwarding rules or proxies in front - and it worked like a charm. This issue can be closed now. Appreciate your help a lot. It also led me to discover couple of things which otherwise would have gone unnoticed till they broke down.

**Comment by willmcgugan** [comment]
Thanks for investigating.
