### ISSUE TITLE
How to send json data over websocket?

### ISSUE THREAD

**Issue by vocabexpresshaxer** [wildfoundry/dataplicity-lomond#74]
Basically, i completely understand most of the documentation, but im still not 100% on how to send json data over the websocket

say i wanted to send
{"name": "bob", "age": 31} over the websocket, how would i do that?

**Comment by rawberg** [comment]
You can use the [send_json](https://lomond.readthedocs.io/en/latest/websocket.html#lomond.websocket.WebSocket.send_json) method.

**Comment by willmcgugan** [comment]
@vocabexpresshaxer Did you get that working? Happy to update docs if it would make it clearer.
