### ISSUE TITLE
Server disconnects regularly

### ISSUE THREAD

**Issue by rjhornsby** [wildfoundry/dataplicity-lomond#75]
My Websocket server is the application ProPresenter 6 (free trial download available if that helps). I'm trying to grab data from the `/stagedisplay` endpoint (127.0.0.1 so LAN/WAN involved), and it's working really well using lomond. I'm getting very close to being able to receive the data I need from ProPresenter to set up some other automation. Thank you!

However, about every 8 seconds or so (give or take `back_off` rate), the server side (PP) sends a TCP RST and lomond has to reconnect. As far as I can tell from looking at the traffic with Wireshark, the ping/pong behavior is correct but that was my first suspicion. Further, I'm able to connect, authenticate, send requests, get responses etc. The disconnections have me a bit baffled though.

Before finding lomond, I grabbed _WebSocket Client_[1] from the Apple App Store. While it's got some frustrating UI issues, it does not seem to suffer from the same disconnects. More specifically, _WebSocket Client_ seems to be doing something that is preventing PP from wanting to send a TCP RST, as per Wireshark. I'm not sure what that magic is.

I've attached a sample Wireshark pcap file (`62576` is the server side port), as well as linked a simple example gist[2] that uses lomond. It seems like there's a bug somewhere in this pile of fun, but I'm not sure where it could be.

[pro6-lomond.pcapng.zip](https://github.com/wildfoundry/dataplicity-lomond/files/2330464/pro6-lomond.pcapng.zip)

[1] https://itunes.apple.com/us/app/websocket-client/id1399498094?mt=12
[2] https://gist.github.com/rjhornsby/ed74d386672abe60896ca93d6534e7a1

**Comment by willmcgugan** [comment]
It doesn't appear that Lomond is misbehaving there. All signs point to either the app, or something between the app and your client. The RST packets usually suggests firewall, or some other network infrastructure. If you have a firewall, you could try disabling it. Another possibility is a misbehaving proxy. If you have a proxy configured, you can tell Lomond not to use it by constructing the WebSocket with `proxies={}`.

**Comment by rjhornsby** [comment]
Thanks for the quick response.

> 127.0.0.1 so LAN/WAN involved

Sorry, I meant to say "..._no_ LAN/WAN involved" - so while they can definitely be a source of trouble, there shouldn't be any proxies or firewalls interfering in this case. To be fair, I do have LittleSnitch running, but it is presently in `Silent Mode - Connections Allowed`. Further, LS is more about blocking connections outright so they can't even get started, rather than interfering with them once they're already established.

I tried to sort of eyeball the packet captures separately to see why _Websocket client_ seems to be okay while Lomond does not, but I'll go through and try to do a more in depth side-by-side packet-by-packet comparison.

**Comment by rjhornsby** [comment]
I think I may have found the "solution".

```
        for event in persist(self.ws, ping_rate=0):
            print(event.name)
```

_Websocket Client_ doesn't attempt to ping the server at all as far as I can tell.

Back to Lomond, assuming that we do not wish to disable client-> server pings entirely, the server wasn't responding to client pings. (Why this made the _server_ send RST I can't explain. It seems like things are going along fine - the server is happy - right up until that moment.) That is, Lomond never saw a `pong` event. Digging deeper, it looks as if the server is ignoring a `ping` request that has no data. This is the default behavior for `send_ping()`.

As soon as I changed the [websocket.py::send_ping()](https://github.com/wildfoundry/dataplicity-lomond/blob/master/lomond/websocket.py#L430) method to default to having data, any data, the disconnects cease, and pong events show up as expected.

`def send_ping(self, data=b'foo'):`

The [RFC](
https://tools.ietf.org/html/rfc6455#section-5.5.3) does not appear to require data, only that the `pong` must contain the same data sent 

> A Pong frame sent in response to a Ping frame must have identical
> "Application data" as found in the message body of the Ping frame
> being replied to.

If I had to put fault somewhere, I'd have to say the server side should reasonably be expected to reply to a `ping` even if there was no data. However, I'm stuck with the server implementation as it is, and everything else seems to work as it should.

If I were to propose a fix, I think that maybe the simplest solution is to make it so that the `data` arg of `websocket.py::send_ping()` defaults to something other than empty? I'm looking at how it might be possible to instead pass an additional argument from `connect()` through the stack (with `ping_rate`, `ping_timeout`) etc - ie `ping_data` but that's a bit more involved.

I suppose I could set `ping_rate=0` and then from the perspective of being a Lomond client, just manually call `send_ping()` with data every X interval, but that kind of defeats the purpose of all of Lomond's work behind the scenes to manage regularly scheduled pings and pongs.

**Comment by willmcgugan** [comment]
Thanks for digging!

An empty ping is valid, but I'd guess that the app developer didn't know that.

From your point of view, disabling the pings may just be an adequate solution. Chances are the server doesn't even need them. If you wanted to restore pings, you could send a ping in response to a poll event.

I'm not too keen on changing the default ping, as an empty ping should be adequate. And sending the smallest packet is probably a sensible default. However this does raise an interesting point that the developer may want to be able to set the ping data without a workaround. It should probably be exposed in a more dynamic way and not just a constant. I'm going to file a separate issue for that.

Will close this issue for now. I'm assuming that you're happy with a workaround?

**Comment by willmcgugan** [comment]
https://github.com/wildfoundry/dataplicity-lomond/issues/76

**Comment by rjhornsby** [comment]
> If you wanted to restore pings, you could send a ping in response to a poll event.

Thanks for the suggestion. That's a reasonable solution. Since my client is passive, waiting for periodic updates after sending a few initial commands, I'd like to keep client-side pings in play.

> I'm not too keen on changing the default ping, as an empty ping should be adequate. And sending the smallest packet is probably a sensible default.

To be honest, I agree with your assessment. I wasn't too keen on suggesting it for that reason :) I think the flexibility proposed in #76 while maintaining the current behavior as the default is a good approach.
