### ISSUE TITLE
Close a persistent connection

### ISSUE THREAD

**Issue by jebesen** [wildfoundry/dataplicity-lomond#77]
I create a persistent connection so if the connection disconnects for any reason it automatically reconnects.
But I would like to be able to close the connection if I want. Now, if I send a close(), it tries to reconnect.
Is there anyway I can entirely close gracefully the connection in a persistent websocket?

**Comment by willmcgugan** [comment]
The `persist` method has an `exit_event` argument. You can supply a `threading.Event` object, which when set will tell the persist loop not to re-establish the connection. If the websocket closes for any reason, then the iterator will finish.

Something like this:

```python
import threading
exit_event = threading.Event()

for event in persist(ws, exit_event=exit_event):
    if event.name == 'text':
        if event.text == 'QUIT':
            exit_event.set()
            ws.close()
```

Hope that helps.

**Comment by jebesen** [comment]
Thank you very much for your quick response.

First of all, I find lomond the best and more usable websocket library for python.

I am using it as an object and the execution is in a thread, just to execute it in the background while the program continues doing another things.

The basics of my program are this:

```
class MySocket(object):
    def __init__(self):
        self.stop=False

    def start(self):
        def _go():
            self.ws = WebSocket("wss://feed.com")
            self._listen()
        self.stop = False
        self.thread = Thread(target=_go)
        self.thread.start()

    def _listen(self):
        for event in persist(self.ws):
            if event.name == "ready":
                print("Connected")     
            elif event.name == "disconnected":
                print("Disconnected " + event.reason)
            elif event.name == "closed":
                print("Closed: " + event.reason)
            elif event.name == "back_off":
                if self.stop:
                    return
                print("Reconnecting in " + str(event.delay) + " seconds.")

            elif event.name == "text":
                msg = event.json
               print(msg)

    def close(self):
        self.stop = True
        self.ws.close(reason="Closed by app")
```
So I manage to avoid reconnecting using a return in the BackOff event.

I would prefer to use a proper way to exit, but I am a bit lost with all that threading stuff so, since I am running the loop in a thread I do not know how to integrate the solution that you have suggested.
Thanking you anyway.

**Comment by willmcgugan** [comment]
Glad you like Lomond. We have tried to keep it as simple as possible.

@jebesen That may just be good enough if everything happens in the same thread. But if you close the websocket from a another thread, using the exit_event is preferable. It allows you to interrupt the delay between reconnect attempts.

I've modified your code to show how to implement the exit event:

```python
class MySocket(threading.Thread):
    
    def start(self):
        def _go():
            self.ws = WebSocket("wss://feed.com")
            self._listen()
        self.exit_event = threading.Event()
        self.thread = Thread(target=_go)
        self.thread.start()

    def _listen(self):
        for event in persist(self.ws, exit_event=self.exit_event):
            if event.name == "ready":
                print("Connected")     
            elif event.name == "disconnected":
                print("Disconnected " + event.reason)
            elif event.name == "closed":
                print("Closed: " + event.reason)
            elif event.name == "back_off":
                print("Reconnecting in " + str(event.delay) + " seconds.")

            elif event.name == "text":
                msg = event.json
               print(msg)

    def close(self):
        self.exit_event.set()
        self.ws.close(reason="Closed by app")
```

**Comment by jebesen** [comment]
Thank you very much.  Implemented and working!!
