### ISSUE TITLE
Error with Python 3.7

### ISSUE THREAD

**Issue by shred86** [wildfoundry/dataplicity-lomond#79]
[Abodepy](https://github.com/MisterWil/abodepy) uses lomond 0.1.14 to get device updates from the Abode Security System for Home Assistant. If you try to use Python 3.7, there appears to be an error with lomond:

````
Traceback (most recent call last):
  File "/Users/shred/venv/homeassistant/lib/python3.7/site-packages/lomond/stream.py", line 51, in feed
    frame = next(iter_frames)
StopIteration
````

It works fine on Python 3.6.5. I [opened an issue](https://github.com/MisterWil/abodepy/issues/37) on the abodepy page but figured I'd post here as well to see if perhaps it's a known issue or to see if anyone else has used Python 3.7 with lomond.

**Comment by willmcgugan** [comment]
That looks like an issue that was fixed some time ago in https://github.com/wildfoundry/dataplicity-lomond/issues/68. Upgrading Lomond to the latest should fix it.

**Comment by shred86** [comment]
Ah, sorry I completely missed that. Thanks for the info! I'll let the owner of abodepy know.
