### ISSUE TITLE
Can Lomond select clients by "room"?

### ISSUE THREAD

**Issue by milteven12** [wildfoundry/dataplicity-lomond#81]
Hello, there is a python package (websockets) that can create rooms and divide clients for specific rooms, the server can select and send messages based on the rooms or broadcast to all clients besides of the room.

Does lomond has this type of feature?

**Comment by willmcgugan** [comment]
The websocket protocol has no notion of 'rooms'. You may have encountered [socket.io](https://socket.io/) or something like it, which is a service that provides various routing capabilities. 

You will be able to connect to a socket.io server with Lomond, but you will still need to figure out the socket.io protocol to do anything useful...
