### ISSUE TITLE
Not explicitly calling Websocket.connect( ) results in a weird connection state

### ISSUE THREAD

**Issue by royrwood** [wildfoundry/dataplicity-lomond#82]
I ran into an odd problem when I tried to gracefully close my websocket connection.  After much going in circles, I discovered that I never explicitly called connect( ) on the Websocket object, but was able to receive data.  This is confusing, since I was able to get data from the server, even though the connection wasn't really open.  The code I used was based on the sample in the docs, and is reproduced below.

The code was set up to allow me to hit ctrl-C to generate a KeyboardInterrupt and break out of the processing loop.  When that happened, I wanted to close the connection, but process all the close handshaking so the connection shut down gracefully.

With the code as written, the Websocket connection object actually did all the open-connection handshaking AFTER I called the close( ) method!

Things work as expected if I execute something like "ws_event_iter = ws.connect( )" and then do "for event in ws_event_iter".  That opens the websocket connection and makes the close( ) call trigger a graceful shutdown of the connection.

<pre>
from __future__ import print_function

from lomond.websocket import WebSocket

ws = WebSocket('ws://localhost:15674/ws')

try:
    for event in ws:
          print('EVENT: %s', event)

except KeyboardInterrupt:                
    print('Closing websocket')
    
    ws.close()
    
    for event in ws:
        print('CLOSING EVENT: %s', event)
</pre>

Running the code as shown results in the following:

<pre>
$ python test.py 
EVENT: %s Connecting(url='ws://localhost:15674/ws')
EVENT: %s Connected(url='ws://localhost:15674/ws')
EVENT: %s Ready(response=<response HTTP/1.1 101 Switching Protocols>, protocol=None, extensions=set([]))
EVENT: %s Poll()
EVENT: %s Pong(data='')
EVENT: %s Poll()
^CClosing websocket
CLOSING EVENT: %s Connecting(url='ws://localhost:15674/ws')
CLOSING EVENT: %s Connected(url='ws://localhost:15674/ws')
CLOSING EVENT: %s Ready(response=<response HTTP/1.1 101 Switching Protocols>, protocol=None, extensions=set([]))
CLOSING EVENT: %s Poll()
CLOSING EVENT: %s Pong(data='')
CLOSING EVENT: %s Poll()
</pre>

Adding an explicit connect( ) call like this results in a clean close...

<pre>
from __future__ import print_function

from lomond.websocket import WebSocket

ws = WebSocket('ws://localhost:15674/ws')
ws_event_iter = ws.connect()

try:
    for event in ws_event_iter:
          print('EVENT: %s', event)

except KeyboardInterrupt:
    print('Closing websocket')

    ws.close()

    for event in ws_event_iter:
        print('CLOSING EVENT: %s', event)

    print('Websocket closed cleanly, no more events.')
</pre>

And here's the output:

<pre>
$ python test.py 
EVENT: %s Connecting(url='ws://localhost:15674/ws')
EVENT: %s Connected(url='ws://localhost:15674/ws')
EVENT: %s Ready(response=<response HTTP/1.1 101 Switching Protocols>, protocol=None, extensions=set([]))
EVENT: %s Poll()
EVENT: %s Pong(data='')
EVENT: %s Poll()
^CClosing websocket
Websocket closed cleanly, no more events.
</pre>

**Comment by willmcgugan** [comment]
Hi @royrwood,

When you do `for event in ws` it will implicitly call `connect`. When the forloop exists due to an exception, it will close the socket and do an *ungraceful close*.

So your first example, the original websocket is closed when you get the KeyboardInterupt. You then open a new connection to the server within the exception handler.

In your second example you get an iterator which powers the websocket. This gives you a bit more flexibility, since you can iterator over it a second time without reconnecting.

If your goal is to do a graceful close after pressing Ctrl+C, then your second solution is good. It's not essential to do that, but it does allow the server to finish sending you data before it closes.

Hope that helps!

**Comment by royrwood** [comment]
@willmcgugan -- thanks for the quick reply!  That makes sense.

Is the automatic-disconnect behaviour in response to an exception documented?  If not, then it would be nice to add that in case someone else bumps into this problem in the future.

And thanks for all the work on lomond.  It has been fantastically useful!

**Comment by willmcgugan** [comment]
It is covered briefly at the end of https://lomond.readthedocs.io/en/latest/guide.html#events

But perhaps it's not clear. Feel free to open a documentation PR if you think it could be worded better.

Glad you found Lomond useful :)

**Comment by royrwood** [comment]
Ah-- so I should have read the friendly manual more closely.  :-)

What's the quote?  Something like "Remember that hours of trial and error can save you minutes of reading the documentation."

Thanks!  All good!
