### ISSUE TITLE
wamp

### ISSUE THREAD

**Issue by snapo** [wildfoundry/dataplicity-lomond#87]
Is there a way to connect to a wamp based server? Its also a websocket but the handling is different.
http://zderadicka.eu/wamp-is-websocket-on-steroids/

currently all my tests failed to even connect ;=) maybe you have a few inputs what else i could try.

**Comment by snapo** [comment]
its was because the server sent a 301 return code "permanently moved".... so solved.

**Comment by barfle** [comment]
Glad to hear you got it resolved :-)
